language: python
sudo: false
env:
  - LUA="luajit=2.0"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
install:
  - make setup
  - make install
deploy:
  - provider: script
    skip_cleanup: true
    script: luarocks upload kong-plugin-url-rewrite-*.rockspec --api-key=$LUAROCKS_API_KEY
    on:
      branch: legacy/v0
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - make test
