name: "Test"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kongVersion:
          - "3.7.1.2"

    steps:
      - uses: actions/checkout@v4

      - uses: Kong/kong-pongo-action@5972effad7a566aed12b879b559bbff07d258d51
        with:
          pongo_version: 2.18.0
          kong_version: ${{ matrix.kongVersion }}

      - run: pongo run -- --Xoutput "--color" --coverage
