name: PublishPlugin

on:
  push:
    branches: [main, legacy/v0]

  workflow_dispatch:

env:
  LUA: "lua=5.1"
  GCP_PROJECT_ID: "si26ef9dii9zscrxrecql6kl8eguw2"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Create PR: Merge main into develop branch'
        id: create-develop-pull-request
        uses: thomaseizinger/create-pull-request@1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: main
          base: develop
          labels: develop
          title: Merge main into develop branch
          body: |
            This PR merges the main branch back into develop.
            This happens to ensure that the updates that happend on the release branch, i.e. CHANGELOG and manifest updates are also present on the develop branch.

      - name: before install
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev luarocks
          sudo pip install hererocks
          sudo hererocks lua_install -r^ --${{ env.LUA }}
          export PATH=$PATH:$PWD/lua_install/bin

      - name: install
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          sudo make setup
          sudo make install

      - name: test
        run: |
          sudo make test

      - name: GCP Auth
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Get Luarocks API Key
        id: luarocks-key
        uses: google-github-actions/get-secretmanager-secrets@v0.2.2
        with:
          secrets: |-
            LUAROCKS_API_KEY:${{ env.GCP_PROJECT_ID }}/LUAROCKS_APIKEY

      - name: deploy
        run: |
          luarocks upload kong-plugin-url-rewrite-*.rockspec --api-key=${{ steps.luarocks-key.outputs.LUAROCKS_API_KEY }}
